import os
import json
import base64
from google import genai
from flask_cors import CORS
from google.genai import types
from flask import Flask, request, jsonify

app = Flask(__name__)
CORS(app)

client = genai.Client(api_key=os.environ.get("GEMINI_API_KEY"))

@app.route('/analyze', methods=['POST'])
def analyze_content():
    data = request.json
    
    text_input = data.get('text')
    image_input = data.get('image') or data.get('file')

    if not text_input and not image_input:
        return jsonify({"error": "No text or image provided"}), 400

    try:
        model_name = "gemini-2.5-flash"
        
        if text_input:
            prompt_content = text_input
            system_instruction = """
            You are a forensic fact-checker. Analyze the text provided.
            """

        else:
            try:
                if "," in image_input:
                    image_input = image_input.split(",")[1]
                
                image_bytes = base64.b64decode(image_input)
            except Exception as e:
                return jsonify({"error": "Invalid image data", "details": str(e)}), 400

            prompt_content = types.Part.from_bytes(
                data=image_bytes,
                mime_type="image/png"
            )

            system_instruction = """
            You are a forensic fact-checker. You will be provided with an image (likely a screenshot of a tweet or post).
            1. Extract the main text content from the image.
            2. Analyze that text to determine if it was generated by an AI/LLM.
            3. Look for visual anomalies in the screenshot (bad fonts, weird layout) that might indicate a fake screenshot.
            """

        final_prompt = """
        Analyze the authenticity of the content. Look for: overly formal tone, lack of personal anecdote, repetitive sentence structure, and 'hallucination' patterns.
        
        Return ONLY a raw JSON object (no markdown formatting) with this structure:
        {
            "score": (integer 0-100, where 100 is highly likely FAKE/AI),
            "verdict": "Human" | "AI-Generated" | "Mixed" | "Unsure",
            "reasoning": "Short explanation of why. If it was an image, mention if the text matches the visual context.",
            "sources": ["List of sources if found, or 'None found'"],
            "indicators": ["list of specific phrases or patterns found"]
        }
        """

        response = client.models.generate_content(
            model=model_name,
            contents=[prompt_content, final_prompt],
            config=types.GenerateContentConfig(
                system_instruction=system_instruction,
                response_mime_type="application/json"
            )
        )
        
        result = json.loads(response.text)
        
        return jsonify(result)

    except Exception as e:
        print(f"Server Error: {str(e)}")
        
        return jsonify({"error": "Analysis failed", "details": str(e)}), 500

if __name__ == '__main__':
    port = int(os.environ.get("PORT", 5000))
    
    app.run(host='0.0.0.0', port=port)